name: Build & Release Thunderbird Add-on

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip make

      - name: Build XPI
        run: make xpi

      - name: Upload XPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderbird-addon
          path: dist/minimizeonclose.xpi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/minimizeonclose.xpi
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
